<?php

return [
    'roles' => [
        'owner' => 'Owner',
        'admin' => 'Admin',
        'receptionist' => 'Receptionist',
        'professional' => 'Professional',
    ],

    'trial' => [
        'days' => 14,
        'entitlements' => [
            'appointment.create' => true,
            'client.manage' => true,
            'service.manage' => true,
            'professional.manage' => true,
            'resource.manage' => true,
            'public_booking.enabled' => true,
            'whatsapp_link.enabled' => true,
            'whatsapp_auto.enabled' => true,
            'automation.enabled' => true,
            'reports.basic' => true,
            'reports.advanced' => true,
            'clinical.enabled' => true,
            'team.manage' => true,
            'branch.manage' => true,
        ],
        'limits' => [
            'monthly_appointments' => 120,
            'professionals' => 6,
            'services' => 20,
            'branches' => 2,
            'users' => 3,
            'resources' => 12,
        ],
    ],

    'modules' => [
        'agenda' => ['label' => 'Agenda', 'icon' => 'calendar', 'status' => 'Funcional', 'route' => 'agenda.index', 'entitlement' => 'appointment.create', 'summary' => 'Vista operativa para citas, bloqueos y disponibilidad.'],
        'clientes' => ['label' => 'Clientes', 'icon' => 'users', 'status' => 'Funcional', 'route' => 'clientes.index', 'entitlement' => 'client.manage', 'summary' => 'Base de clientes con historial y datos de contacto.'],
        'historia_clinica' => [
            'label' => 'Historia clinica',
            'icon' => 'heart',
            'status' => 'Funcional',
            'route' => 'clinical-records.index',
            'entitlement' => 'clinical.enabled',
            'summary' => 'Evoluciones, diagnosticos, planes y recomendaciones por paciente.',
            'available_for_industries' => ['salud', 'fisioterapia', 'fisio', 'spa', 'veterinaria', 'estetica', 'medicina', 'odontologia', 'psicologia', 'terapia', 'rehabilitacion'],
        ],
        'servicios' => ['label' => 'Servicios', 'icon' => 'briefcase', 'status' => 'Funcional', 'route' => 'servicios.index', 'entitlement' => 'service.manage', 'summary' => 'Catalogo inicial preparado para servicios por empresa.'],
        'profesionales' => ['label' => 'Profesionales', 'icon' => 'users', 'status' => 'Funcional', 'route' => 'profesionales.index', 'entitlement' => 'professional.manage', 'summary' => 'Equipo asociado a sedes, horarios y futuras agendas.'],
        'recursos' => ['label' => 'Recursos', 'icon' => 'box', 'status' => 'Funcional', 'route' => 'recursos.index', 'entitlement' => 'resource.manage', 'summary' => 'Cabinas, equipos, consultorios u otros recursos reservables.'],
        'automatizaciones' => ['label' => 'Automatizaciones', 'icon' => 'zap', 'status' => 'Funcional', 'route' => 'automations.index', 'entitlement' => 'automation.enabled', 'summary' => 'Plantillas y recordatorios operativos para citas.'],
        'compartir' => ['label' => 'Compartir reservas', 'icon' => 'share', 'status' => 'Funcional', 'route' => 'sharing.index', 'entitlement' => 'public_booking.enabled', 'summary' => 'Enlaces publicos, QR, mensajes sugeridos y checklist para salir a vender.'],
        'contacto_whatsapp' => ['label' => 'Contacto WhatsApp', 'icon' => 'message', 'status' => 'Funcional', 'route' => 'whatsapp-contact.index', 'entitlement' => 'whatsapp_link.enabled', 'summary' => 'Bandeja manual para contactar clientes, confirmar cambios y operar WhatsApp.'],
        'whatsapp_automatico' => ['label' => 'WhatsApp automatico', 'icon' => 'message', 'status' => 'Funcional', 'route' => 'whatsapp-activation.create', 'entitlement' => 'whatsapp_auto.enabled', 'summary' => 'Solicitud administrada para que TREBBIA active WhatsApp automatico sin friccion para el negocio.'],
        'whatsapp_demo' => ['label' => 'WhatsApp demo', 'icon' => 'message', 'status' => 'Funcional', 'route' => 'whatsapp-simulator.index', 'entitlement' => 'whatsapp_link.enabled', 'summary' => 'Simulador interno para probar conversaciones y reservas sin conectar Meta.'],
        'reportes' => ['label' => 'Reportes', 'icon' => 'bar-chart', 'status' => 'Funcional', 'route' => 'reports.index', 'entitlement' => 'reports.basic', 'summary' => 'Indicadores de citas, ingresos estimados, servicios, profesionales y clientes.'],
        'membresia' => ['label' => 'Membresia', 'icon' => 'credit-card', 'status' => 'Funcional', 'route' => 'membership.index', 'summary' => 'Plan actual, uso del negocio y limites comerciales.'],
        'configuracion' => ['label' => 'Configuracion', 'icon' => 'settings', 'status' => 'Funcional', 'route' => 'settings.index', 'summary' => 'Perfil del negocio, sedes, usuarios base y parametros de agenda.'],
    ],

    'plans' => [
        [
            'name' => 'TREBBIA Esencial',
            'code' => 'essential',
            'description' => 'Para negocios pequenos que necesitan operar agenda, clientes y reservas sin complejidad.',
            'currency' => 'COP',
            'monthly_price_cents' => 5900000,
            'annual_price_cents' => 59000000,
            'sort_order' => 10,
            'limits' => [
                'monthly_appointments' => 150,
                'professionals' => 3,
                'services' => 12,
                'branches' => 1,
                'users' => 2,
                'resources' => 6,
            ],
            'entitlements' => [
                'appointment.create' => true,
                'client.manage' => true,
                'service.manage' => true,
                'professional.manage' => true,
                'resource.manage' => true,
                'public_booking.enabled' => true,
                'whatsapp_link.enabled' => true,
                'whatsapp_auto.enabled' => false,
                'automation.enabled' => false,
                'reports.basic' => true,
                'reports.advanced' => false,
                'clinical.enabled' => true,
                'team.manage' => true,
                'branch.manage' => false,
            ],
            'features' => ['Agenda y citas', 'Clientes e historial', 'Reservas publicas', 'Enlace de WhatsApp', 'Reportes basicos'],
        ],
        [
            'name' => 'TREBBIA Profesional',
            'code' => 'professional',
            'description' => 'Para equipos que necesitan mas capacidad, automatizaciones y control operativo.',
            'currency' => 'COP',
            'monthly_price_cents' => 9900000,
            'annual_price_cents' => 99000000,
            'sort_order' => 20,
            'limits' => [
                'monthly_appointments' => 500,
                'professionals' => 8,
                'services' => 25,
                'branches' => 3,
                'users' => 5,
                'resources' => 20,
            ],
            'entitlements' => [
                'appointment.create' => true,
                'client.manage' => true,
                'service.manage' => true,
                'professional.manage' => true,
                'resource.manage' => true,
                'public_booking.enabled' => true,
                'whatsapp_link.enabled' => true,
                'whatsapp_auto.enabled' => true,
                'automation.enabled' => true,
                'reports.basic' => true,
                'reports.advanced' => true,
                'clinical.enabled' => true,
                'team.manage' => true,
                'branch.manage' => true,
            ],
            'features' => ['Agenda avanzada', 'Automatizaciones', 'WhatsApp automatico asistido', 'Reportes completos', 'Equipo y sedes'],
        ],
        [
            'name' => 'TREBBIA Empresarial',
            'code' => 'enterprise',
            'description' => 'Para operaciones con varias sedes, mayor volumen y acompanamiento prioritario.',
            'currency' => 'COP',
            'monthly_price_cents' => 17900000,
            'annual_price_cents' => 179000000,
            'sort_order' => 30,
            'limits' => [
                'monthly_appointments' => null,
                'professionals' => null,
                'services' => null,
                'branches' => null,
                'users' => null,
                'resources' => null,
            ],
            'entitlements' => [
                'appointment.create' => true,
                'client.manage' => true,
                'service.manage' => true,
                'professional.manage' => true,
                'resource.manage' => true,
                'public_booking.enabled' => true,
                'whatsapp_link.enabled' => true,
                'whatsapp_auto.enabled' => true,
                'automation.enabled' => true,
                'reports.basic' => true,
                'reports.advanced' => true,
                'clinical.enabled' => true,
                'team.manage' => true,
                'branch.manage' => true,
            ],
            'features' => ['Uso ampliado', 'Multiples sedes', 'Equipo completo', 'Soporte prioritario', 'Base para CRM e IA'],
        ],
    ],

    'service_presets' => [
        'default' => [
            ['name' => 'Consulta inicial', 'duration_minutes' => 60, 'price' => 80000, 'description' => 'Primera atencion para conocer la necesidad del cliente.'],
            ['name' => 'Servicio estandar', 'duration_minutes' => 45, 'price' => 70000, 'description' => 'Atencion principal del negocio.'],
            ['name' => 'Seguimiento', 'duration_minutes' => 30, 'price' => 50000, 'description' => 'Cita corta para control, ajuste o continuidad.'],
        ],
        'fisioterapia' => [
            ['name' => 'Valoracion inicial', 'duration_minutes' => 60, 'price' => 90000, 'description' => 'Evaluacion inicial del paciente y definicion del plan de tratamiento.'],
            ['name' => 'Fisioterapia traumatologica', 'duration_minutes' => 60, 'price' => 85000, 'description' => 'Sesion enfocada en lesiones musculares, articulares o postoperatorias.'],
            ['name' => 'Rehabilitacion deportiva', 'duration_minutes' => 60, 'price' => 95000, 'description' => 'Trabajo de recuperacion y retorno progresivo a la actividad fisica.'],
            ['name' => 'Terapia manual', 'duration_minutes' => 45, 'price' => 80000, 'description' => 'Sesion de tecnicas manuales para movilidad, dolor y funcion.'],
        ],
        'salud' => [
            ['name' => 'Consulta inicial', 'duration_minutes' => 60, 'price' => 90000, 'description' => 'Primera valoracion y apertura de proceso de atencion.'],
            ['name' => 'Control', 'duration_minutes' => 30, 'price' => 60000, 'description' => 'Seguimiento de evolucion, recomendaciones y ajustes.'],
            ['name' => 'Procedimiento ambulatorio', 'duration_minutes' => 45, 'price' => 120000, 'description' => 'Atencion programada con preparacion y registro clinico.'],
        ],
        'belleza' => [
            ['name' => 'Limpieza facial', 'duration_minutes' => 60, 'price' => 120000, 'description' => 'Tratamiento facial base para limpieza y cuidado de piel.'],
            ['name' => 'Masaje relajante', 'duration_minutes' => 60, 'price' => 110000, 'description' => 'Sesion de bienestar y relajacion corporal.'],
            ['name' => 'Tratamiento corporal', 'duration_minutes' => 75, 'price' => 160000, 'description' => 'Atencion corporal especializada segun necesidad del cliente.'],
            ['name' => 'Valoracion estetica', 'duration_minutes' => 30, 'price' => 50000, 'description' => 'Revision inicial y recomendacion de tratamiento.'],
        ],
        'spa' => [
            ['name' => 'Masaje relajante', 'duration_minutes' => 60, 'price' => 120000, 'description' => 'Sesion de relajacion y bienestar.'],
            ['name' => 'Ritual spa', 'duration_minutes' => 90, 'price' => 220000, 'description' => 'Experiencia completa con preparacion, tratamiento y cierre.'],
            ['name' => 'Limpieza facial', 'duration_minutes' => 60, 'price' => 130000, 'description' => 'Cuidado facial base para limpieza profunda.'],
        ],
        'barberia' => [
            ['name' => 'Corte clasico', 'duration_minutes' => 30, 'price' => 35000, 'description' => 'Corte de cabello tradicional o moderno.'],
            ['name' => 'Corte y barba', 'duration_minutes' => 50, 'price' => 55000, 'description' => 'Servicio combinado de cabello y arreglo de barba.'],
            ['name' => 'Barba', 'duration_minutes' => 25, 'price' => 25000, 'description' => 'Perfilado, arreglo o afeitado de barba.'],
            ['name' => 'Diseno de cejas', 'duration_minutes' => 15, 'price' => 15000, 'description' => 'Perfilado rapido de cejas.'],
        ],
        'restaurante' => [
            ['name' => 'Reserva de mesa', 'duration_minutes' => 90, 'price' => 0, 'description' => 'Reserva estandar para atencion en sala.'],
            ['name' => 'Celebracion especial', 'duration_minutes' => 120, 'price' => 0, 'description' => 'Reserva para cumpleanos, aniversario o reunion especial.'],
            ['name' => 'Evento privado', 'duration_minutes' => 180, 'price' => 0, 'description' => 'Bloque de atencion para grupos o eventos.'],
        ],
        'servicios profesionales' => [
            ['name' => 'Consulta inicial', 'duration_minutes' => 60, 'price' => 120000, 'description' => 'Reunion inicial para entender la necesidad y definir alcance.'],
            ['name' => 'Asesoria especializada', 'duration_minutes' => 60, 'price' => 180000, 'description' => 'Sesion de trabajo con recomendacion profesional.'],
            ['name' => 'Seguimiento', 'duration_minutes' => 30, 'price' => 90000, 'description' => 'Revision corta de avances, pendientes o decisiones.'],
        ],
    ],

    'industry_modules' => [
        'default' => ['Agenda', 'Clientes', 'Servicios', 'Compartir reservas', 'Contacto WhatsApp'],
        'fisioterapia' => ['Agenda', 'Clientes', 'Historia clinica', 'Recursos', 'Compartir reservas', 'Contacto WhatsApp'],
        'salud' => ['Agenda', 'Clientes', 'Historia clinica', 'Recursos', 'Compartir reservas', 'Contacto WhatsApp'],
        'belleza' => ['Agenda', 'Clientes', 'Recursos', 'Automatizaciones', 'Compartir reservas', 'Contacto WhatsApp'],
        'spa' => ['Agenda', 'Clientes', 'Recursos', 'Automatizaciones', 'Compartir reservas', 'Contacto WhatsApp'],
        'barberia' => ['Agenda', 'Clientes', 'Profesionales', 'Recursos', 'Compartir reservas', 'Contacto WhatsApp'],
        'restaurante' => ['Agenda', 'Clientes', 'Recursos', 'Reportes', 'Compartir reservas', 'Contacto WhatsApp'],
        'servicios profesionales' => ['Agenda', 'Clientes', 'Servicios', 'Automatizaciones', 'Reportes', 'Contacto WhatsApp'],
    ],

    'resource_presets' => [
        'default' => [
            ['name' => 'Sala 1', 'type' => 'Sala'],
            ['name' => 'Consultorio 1', 'type' => 'Consultorio'],
            ['name' => 'Equipo principal', 'type' => 'Equipo'],
        ],
        'fisioterapia' => [
            ['name' => 'Consultorio fisioterapia 1', 'type' => 'Consultorio'],
            ['name' => 'Camilla 1', 'type' => 'Equipo'],
            ['name' => 'Camilla 2', 'type' => 'Equipo'],
            ['name' => 'Sala de rehabilitacion', 'type' => 'Sala'],
            ['name' => 'Equipo de electroterapia', 'type' => 'Equipo'],
        ],
        'salud' => [
            ['name' => 'Consultorio 1', 'type' => 'Consultorio'],
            ['name' => 'Consultorio 2', 'type' => 'Consultorio'],
            ['name' => 'Sala de procedimientos', 'type' => 'Sala'],
            ['name' => 'Equipo de diagnostico', 'type' => 'Equipo'],
        ],
        'belleza' => [
            ['name' => 'Cabina 1', 'type' => 'Cabina'],
            ['name' => 'Cabina 2', 'type' => 'Cabina'],
            ['name' => 'Camilla estetica', 'type' => 'Equipo'],
            ['name' => 'Equipo facial', 'type' => 'Equipo'],
        ],
        'barberia' => [
            ['name' => 'Silla 1', 'type' => 'Puesto'],
            ['name' => 'Silla 2', 'type' => 'Puesto'],
            ['name' => 'Lavacabezas', 'type' => 'Equipo'],
        ],
        'restaurante' => [
            ['name' => 'Mesa 1', 'type' => 'Mesa'],
            ['name' => 'Mesa 2', 'type' => 'Mesa'],
            ['name' => 'Salon principal', 'type' => 'Salon'],
        ],
    ],
];
